name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
      pages: write
      id-token: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build and Deploy
        uses: ./.github/actions/build-and-deploy
        with:
          notion_api_key: ${{ secrets.NOTION_API_KEY }}
          database_id: ${{ secrets.DATABASE_ID }}
          website_tag: ${{ secrets.WEBSITE_TAG }}
          base_url: /${{ github.event.repository.name }}
