name: Update Content

on:
  schedule:
    - cron: ${{ inputs.cron || '*/1 * * * *' }}  # Run every minute by default
  workflow_dispatch:
    inputs:
      cron:
        description: 'Cron schedule'
        required: false
        default: '*/1 * * * *'

env:
  NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
  DATABASE_ID: ${{ secrets.DATABASE_ID }}
  WEBSITE_TAG: ${{ secrets.WEBSITE_TAG }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest

    - name: Install dependencies
      run: bun install
      env:
        NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
        DATABASE_ID: ${{ secrets.DATABASE_ID }}
        WEBSITE_TAG: ${{ secrets.WEBSITE_TAG }}

    - name: Build project
      run: bun run build
      env:
        NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
        DATABASE_ID: ${{ secrets.DATABASE_ID }}
        WEBSITE_TAG: ${{ secrets.WEBSITE_TAG }}

    - name: Commit and push if changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        git diff --quiet && git diff --staged --quiet || (git commit -m "Auto-update content" && git push)
