name: Update Content

on:
  schedule:
    - cron: ${{ inputs.cron || '*/1 * * * *' }}  # Run every minute by default
  workflow_dispatch:
    inputs:
      cron:
        description: 'Cron schedule'
        required: false
        default: '*/1 * * * *'

env:
  MY_ENV_VAR1: ${{ secrets.MY_ENV_VAR1 }}
  MY_ENV_VAR2: ${{ secrets.MY_ENV_VAR2 }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest

    - name: Install dependencies
      run: bun install

    - name: Build project
      run: bun run build
      env:
        MY_ENV_VAR1: ${{ env.MY_ENV_VAR1 }}
        MY_ENV_VAR2: ${{ env.MY_ENV_VAR2 }}

    - name: Commit and push if changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        git diff --quiet && git diff --staged --quiet || (git commit -m "Auto-update content" && git push)
