name: Update Content

on:
  schedule:
    - cron: '*/10 * * * *'  # Run every 10 minutes
  workflow_dispatch:
    inputs:
      cron:
        description: 'Cron schedule'
        required: false
        default: '*/1 * * * *'
      NOTION_API_KEY:
        description: 'Notion API Key'
        required: false
      DATABASE_ID:
        description: 'Database ID'
        required: false
      WEBSITE_TAG:
        description: 'Website Tag'
        required: false

env:
  NOTION_API_KEY: ${{ inputs.NOTION_API_KEY || secrets.NOTION_API_KEY }}
  DATABASE_ID: ${{ inputs.DATABASE_ID || secrets.DATABASE_ID }}
  WEBSITE_TAG: ${{ inputs.WEBSITE_TAG || secrets.WEBSITE_TAG }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest

    - name: Install dependencies
      run: bun install

    - name: Build project
      run: bun run build

    - name: Commit and push if changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        git diff --quiet && git diff --staged --quiet || (git commit -m "Auto-update content" && git push)
